version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: fenix-redis
    volumes:
      - $PWD/redis-data:/data/rdb
      ports:
        - "6379:6379"
  mongo-database:
    image: mongo:latest
    container_name: fenix-mongodb
    volumes:
     - $PWD/mongo-data:/data/db
    ports:
     - "27017:27017"
  web:
    build: .
    ports:
      - "8000:8000"