version: "3.9"
services:
  web:
    build: ./web
    container_name: fsec_web
    ports:
      - "8080:8080"
  server:
    build: ./server
    container_name: fsec_server
    ports:
        - "8000:8000"
  redis:
    image: "redis:alpine"
    container_name: redis_1
    ports:
      - "6379:6379"
    volumes:
      - /opt/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - /opt/redis/data:/data
  mongo:
    image: "mongo:latest"
    container_name: mongo_1
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
