# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hostdiscovery_pb2 as hostdiscovery__pb2


class HostDiscoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.arp_scan = channel.unary_unary(
                '/HostDiscovery/arp_scan',
                request_serializer=hostdiscovery__pb2.Text.SerializeToString,
                response_deserializer=hostdiscovery__pb2.ResultIp.FromString,
                )


class HostDiscoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def arp_scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostDiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'arp_scan': grpc.unary_unary_rpc_method_handler(
                    servicer.arp_scan,
                    request_deserializer=hostdiscovery__pb2.Text.FromString,
                    response_serializer=hostdiscovery__pb2.ResultIp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HostDiscovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HostDiscovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def arp_scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HostDiscovery/arp_scan',
            hostdiscovery__pb2.Text.SerializeToString,
            hostdiscovery__pb2.ResultIp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
